[helm] Add maxUnavailable option for rolling updates
jtblin/kube2iam pull request #291
Opened 2020-11-23 12:31 UTC by hwoarang

Allow user to set maxUnavailable option for rolling updates in order
to speed up deployment times on large clusters.

2020-12-21 05:06 UTC, jtblin commented
cc @mariusv @walkafwalka can you help reviewing helm charts changes pls?

2020-12-21 08:54 UTC, mariusv approved these changes
LGTM 👍

2020-12-21 08:59 UTC, mariusv requested changes
Please add documentation about the `maxUnavailable` on the readme on how it will be used.

2020-12-23 21:39 UTC, walkafwalka commented
I prefer using something more flexible for updateStrategy but that would require a breaking change. We should take note of situations like this.
```
  updateStrategy: {}
  #  rollingUpdate:
  #    maxUnavailable: 1
  #  type: RollingUpdate
```

Besides the documentation, LGTM.

2021-01-05 19:37 UTC, rdelpret commented
@walkafwalka I 100% agree, I reached out to @mariusv on slack about it to propose the same before I saw this PR but didn't get an answer.

2021-01-05 19:38 UTC, rdelpret commented
Regardless of implementation, this one is urgent for us as large clusters need some pretty high timeouts set w/ helm to get through a rolling update with the hard-coded settings.

2021-01-05 20:49 UTC, rdelpret commented on charts/kube2iam/values.yaml
> +maxUnavailable: 25%
if the breaking change proposed by @walkafwalka is not implemented I think this value should be optional /conditional in the template and commented out. Or it set to the default value which would be `1` for a daemonset according to https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/. You don't want to change this value out from under people.

2021-01-13 11:21 UTC, hwoarang commented
I have updated the default value and added the missing doc. I opted not to implement the braking change at this point. However, if you think we should do it then I can do that no problem

2021-01-19 16:38 UTC, walkafwalka approved these changes

2021-01-26 17:46 UTC, merged